# Site settings
title = "Simon Brand"
email = "tartanllama@gmail.com"
description = "Personal blog and CV for Simon Brand"
baseurl = ""
url = "http =//tartanllama.github.io"
title_description = "Programming blog and CV for Simon Brand, AKA TartanLlama. Expect C++ template metaprogramming."
title_image = "https =//s.gravatar.com/avatar/c425873f547d93f4079ca252b42a886d?s=500"
post_limit = "5"

# Social usernames/URLs
twitter_username = "TartanLlama"
github_username =  "TartanLLama"
linkedin_link = "https://www.linkedin.com/in/simon-brand-36520857"
stackoverflow_link = "http://stackoverflow.com/users/496161/tartanllama"
disqus_account = "tartan-llama"
google_analytics = "UA-86837989-1"

# Footer
footer_left = "<a href=\"https://github.com/jacobtomlinson/carte-noire\">Carte Noir</a> theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right = "&lt;/&gt; on <a href=\"https://github.com/tartanllama/tartanllama.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

#RSS
name = "Simon Brand's Blog"
