language: cpp

compiler: gcc

git:
  submodules: false

before_install:
    - sed -i'.bu' 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - git clone https://github.com/TartanLlama/gcc7-bin-travis.git

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=../gcc7-bin-travis/bin/g++ -DCMAKE_CXX_FLAGS="-L ../gcc7-bin-travis/lib64" .. && make
