language: cpp

compiler: gcc

git:
  submodules: false

before_install:
    - sed -i'.bu' 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - sudo add-apt-repository 'deb http://ftp.de.debian.org/debian experimental main' -y
    - sudo apt-get update
    - sudo apt-get install gcc-7

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=`pwd`/../gcc7-bin-travis/bin/g++ -DCMAKE_CXX_FLAGS="-L `pwd`/../gcc7-bin-travis/lib64" .. && make
